// <auto-generated />
using System;
using BlazorApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            BirthDate = new DateTime(1974, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "MHSN27",
                            HireDate = new DateTime(1998, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "MHSN",
                            Position = "Sales",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 2,
                            BirthDate = new DateTime(1979, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sohel",
                            HireDate = new DateTime(2005, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Shaikh",
                            Position = "Project Manager",
                            State = "Texas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 3,
                            BirthDate = new DateTime(1980, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mark",
                            HireDate = new DateTime(2006, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnnah",
                            Position = "HR Manager",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 4,
                            BirthDate = new DateTime(1968, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "JB",
                            HireDate = new DateTime(1995, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "_",
                            Position = "IT Manager",
                            State = "Arkansas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 5,
                            BirthDate = new DateTime(1953, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hugo",
                            HireDate = new DateTime(1980, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sanchez",
                            Position = "Shipping Manager",
                            State = "Georgia",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 6,
                            BirthDate = new DateTime(1953, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zabi",
                            HireDate = new DateTime(1982, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rahmani",
                            Position = "Controller",
                            State = "Idaho",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 7,
                            BirthDate = new DateTime(1963, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Edimar",
                            HireDate = new DateTime(1990, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Lopes",
                            Position = "Trainer",
                            State = "Utah",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 8,
                            BirthDate = new DateTime(1980, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Arie",
                            HireDate = new DateTime(2008, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Melans",
                            Position = "Engineer",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 9,
                            BirthDate = new DateTime(1970, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ziya",
                            HireDate = new DateTime(1996, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Çetinkaya",
                            Position = "Project Manager",
                            State = "Missouri",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 10,
                            BirthDate = new DateTime(2005, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thiago",
                            HireDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Medeiros",
                            Position = "HR Assistant",
                            State = "Arkansas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 11,
                            BirthDate = new DateTime(1967, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thanh",
                            HireDate = new DateTime(1993, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen",
                            Position = "Support Assistant",
                            State = "Georgia",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 12,
                            BirthDate = new DateTime(1984, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rahul",
                            HireDate = new DateTime(2010, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Salokhe",
                            Position = "Sales Assistant",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 13,
                            BirthDate = new DateTime(2000, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jing Tarng",
                            HireDate = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Loke",
                            Position = "Data Analyst",
                            State = "Nevada",
                            Title = "Ms."
                        },
                        new
                        {
                            EmployeeId = 14,
                            BirthDate = new DateTime(1987, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Met",
                            HireDate = new DateTime(2013, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "It",
                            Position = "HR Manager",
                            State = "Idaho",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 15,
                            BirthDate = new DateTime(1973, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Md.Ariful",
                            HireDate = new DateTime(2000, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Islam",
                            Position = "Engineer",
                            State = "Utah",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 16,
                            BirthDate = new DateTime(1976, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mo",
                            HireDate = new DateTime(2003, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Canada",
                            Position = "Accountant",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 17,
                            BirthDate = new DateTime(1997, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Altanzurkh",
                            HireDate = new DateTime(2020, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "T",
                            Position = "Controller",
                            State = "Arkansas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 18,
                            BirthDate = new DateTime(1951, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mustafa",
                            HireDate = new DateTime(1978, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "YILDIZ",
                            Position = "HR Manager",
                            State = "Missouri",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 19,
                            BirthDate = new DateTime(1959, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Arief",
                            HireDate = new DateTime(1985, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Fauzi",
                            Position = "IT Manager",
                            State = "Georgia",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 20,
                            BirthDate = new DateTime(1951, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Salvador",
                            HireDate = new DateTime(1977, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Castillo",
                            Position = "Engineer",
                            State = "Idaho",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 21,
                            BirthDate = new DateTime(1961, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Luis",
                            HireDate = new DateTime(1988, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "TC",
                            Position = "Trainer",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 22,
                            BirthDate = new DateTime(1991, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Adeel",
                            HireDate = new DateTime(2015, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Baig",
                            Position = "Accountant",
                            State = "Texas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 23,
                            BirthDate = new DateTime(1971, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Novrita",
                            HireDate = new DateTime(1998, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Inkac",
                            Position = "IT Manager",
                            State = "Utah",
                            Title = "Mrs."
                        },
                        new
                        {
                            EmployeeId = 24,
                            BirthDate = new DateTime(1966, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Felipe",
                            HireDate = new DateTime(1992, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rodríguez",
                            Position = "Data Analyst",
                            State = "Nevada",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 25,
                            BirthDate = new DateTime(1993, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fabian",
                            HireDate = new DateTime(2017, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Cebreros",
                            Position = "Accountant",
                            State = "Arkansas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 26,
                            BirthDate = new DateTime(1970, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alan",
                            HireDate = new DateTime(1997, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Michas",
                            Position = "Support Assistant",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 27,
                            BirthDate = new DateTime(1957, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lucky",
                            HireDate = new DateTime(1984, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "D.Bog",
                            Position = "Controller",
                            State = "Missouri",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 28,
                            BirthDate = new DateTime(1968, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anunu",
                            HireDate = new DateTime(1995, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "",
                            Position = "Engineer",
                            State = "Georgia",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 29,
                            BirthDate = new DateTime(1997, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "KRAK",
                            HireDate = new DateTime(2021, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "08",
                            Position = "Project Manager",
                            State = "Idaho",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 30,
                            BirthDate = new DateTime(1976, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Boonsit",
                            HireDate = new DateTime(2002, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chanpoempoonpol",
                            Position = "Support Assistant",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 31,
                            BirthDate = new DateTime(1979, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Danilo",
                            HireDate = new DateTime(2005, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Romao",
                            Position = "Sales",
                            State = "Texas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 32,
                            BirthDate = new DateTime(1999, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "User",
                            HireDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "4571",
                            Position = "Shipping Manager",
                            State = "Utah",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 33,
                            BirthDate = new DateTime(1976, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Yuri",
                            HireDate = new DateTime(2003, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Svyrydov",
                            Position = "IT Manager",
                            State = "Nevada",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 34,
                            BirthDate = new DateTime(1986, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Omar",
                            HireDate = new DateTime(2012, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Abdelrahim",
                            Position = "Project Manager",
                            State = "Arkansas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 35,
                            BirthDate = new DateTime(1993, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "ADIAN",
                            HireDate = new DateTime(2018, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jan",
                            Position = "IT Manager",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 36,
                            BirthDate = new DateTime(2003, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thiago",
                            HireDate = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Valim",
                            Position = "Accountant",
                            State = "Missouri",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 37,
                            BirthDate = new DateTime(1980, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Suphachai",
                            HireDate = new DateTime(2007, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sompanich",
                            Position = "Support Assistant",
                            State = "Georgia",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 38,
                            BirthDate = new DateTime(1975, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "ArtWork",
                            HireDate = new DateTime(2001, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "211",
                            Position = "Support Assistant",
                            State = "Idaho",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 39,
                            BirthDate = new DateTime(1954, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Johny",
                            HireDate = new DateTime(1981, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Angsana",
                            Position = "IT Manager",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 40,
                            BirthDate = new DateTime(1957, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kommineni",
                            HireDate = new DateTime(1984, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Narendra",
                            Position = "Controller",
                            State = "Texas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 41,
                            BirthDate = new DateTime(1971, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Felipe",
                            HireDate = new DateTime(1998, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ramos",
                            Position = "Project Manager",
                            State = "Utah",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 42,
                            BirthDate = new DateTime(1998, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Maroine",
                            HireDate = new DateTime(2021, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chérif",
                            Position = "Data Analyst",
                            State = "Nevada",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 43,
                            BirthDate = new DateTime(1986, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sana",
                            HireDate = new DateTime(2013, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ullah",
                            Position = "Engineer",
                            State = "Arkansas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 44,
                            BirthDate = new DateTime(1973, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michel",
                            HireDate = new DateTime(2000, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Akebo",
                            Position = "HR Manager",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 45,
                            BirthDate = new DateTime(1981, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Omar",
                            HireDate = new DateTime(2008, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Al-Amoudi",
                            Position = "Shipping Manager",
                            State = "Missouri",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 46,
                            BirthDate = new DateTime(2003, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Louay",
                            HireDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Abdel Maeen",
                            Position = "Sales",
                            State = "Georgia",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 47,
                            BirthDate = new DateTime(1967, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Black-Gold",
                            HireDate = new DateTime(1994, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sarnaut",
                            Position = "Project Manager",
                            State = "Idaho",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 48,
                            BirthDate = new DateTime(1968, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gueye",
                            HireDate = new DateTime(1995, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Abdoulaye",
                            Position = "Accountant",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 49,
                            BirthDate = new DateTime(1989, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Cristian",
                            HireDate = new DateTime(2014, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ferreira",
                            Position = "Engineer",
                            State = "Texas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 50,
                            BirthDate = new DateTime(1972, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amir",
                            HireDate = new DateTime(1999, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Osama",
                            Position = "Accountant",
                            State = "Utah",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 51,
                            BirthDate = new DateTime(1965, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mihai",
                            HireDate = new DateTime(1992, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moisei",
                            Position = "HR Manager",
                            State = "Nevada",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 52,
                            BirthDate = new DateTime(2005, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "AKHOM",
                            HireDate = new DateTime(2024, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "ALY",
                            Position = "HR Assistant",
                            State = "Arkansas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 53,
                            BirthDate = new DateTime(1971, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Banpote",
                            HireDate = new DateTime(1998, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jaruboon",
                            Position = "Support Assistant",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 54,
                            BirthDate = new DateTime(1962, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Abdul Razak",
                            HireDate = new DateTime(1989, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Abdulai",
                            Position = "Sales",
                            State = "Missouri",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 55,
                            BirthDate = new DateTime(2001, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "ELy",
                            HireDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moussa",
                            Position = "Project Manager",
                            State = "Georgia",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 56,
                            BirthDate = new DateTime(1983, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Peter",
                            HireDate = new DateTime(2010, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tharwat",
                            Position = "Support Assistant",
                            State = "Idaho",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 57,
                            BirthDate = new DateTime(1985, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            HireDate = new DateTime(2012, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Programmer",
                            Position = "Accountant",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 58,
                            BirthDate = new DateTime(1969, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Luis",
                            HireDate = new DateTime(1996, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Correa",
                            Position = "Sales",
                            State = "Texas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 59,
                            BirthDate = new DateTime(1965, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            HireDate = new DateTime(1992, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chizoba",
                            Position = "Project Manager",
                            State = "Utah",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 60,
                            BirthDate = new DateTime(2005, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Abdul-Rouf",
                            HireDate = new DateTime(2024, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ammar",
                            Position = "IT Manager",
                            State = "Nevada",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 61,
                            BirthDate = new DateTime(2000, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Norbert",
                            HireDate = new DateTime(2022, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Saint Georges",
                            Position = "Data Analyst",
                            State = "Arkansas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 62,
                            BirthDate = new DateTime(2004, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Trieu",
                            HireDate = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "VNH",
                            Position = "Engineer",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 63,
                            BirthDate = new DateTime(1963, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amr",
                            HireDate = new DateTime(1990, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moh",
                            Position = "Project Manager",
                            State = "Missouri",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 64,
                            BirthDate = new DateTime(2003, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ton",
                            HireDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "",
                            Position = "IT Manager",
                            State = "Georgia",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 65,
                            BirthDate = new DateTime(1957, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Prathamesh",
                            HireDate = new DateTime(1985, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Karande",
                            Position = "IT Manager",
                            State = "Idaho",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 66,
                            BirthDate = new DateTime(1950, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mariano",
                            HireDate = new DateTime(1977, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "T3",
                            Position = "HR Manager",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 67,
                            BirthDate = new DateTime(1989, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rekzon",
                            HireDate = new DateTime(2015, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Aborde",
                            Position = "HR Manager",
                            State = "Texas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 68,
                            BirthDate = new DateTime(1980, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Prottoy",
                            HireDate = new DateTime(2007, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roy",
                            Position = "IT Manager",
                            State = "Utah",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 69,
                            BirthDate = new DateTime(2001, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sahli",
                            HireDate = new DateTime(2023, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "SAHBI",
                            Position = "Project Manager",
                            State = "Nevada",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 70,
                            BirthDate = new DateTime(1977, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Onur",
                            HireDate = new DateTime(2004, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Hos",
                            Position = "Controller",
                            State = "Arkansas",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 71,
                            BirthDate = new DateTime(1978, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Armando",
                            HireDate = new DateTime(2005, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Villagomez",
                            Position = "Data Analyst",
                            State = "California",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 72,
                            BirthDate = new DateTime(1988, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jesus Alberto",
                            HireDate = new DateTime(2014, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Roque Ortiz",
                            Position = "Support Assistant",
                            State = "Missouri",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 73,
                            BirthDate = new DateTime(1964, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Md Shahin",
                            HireDate = new DateTime(1991, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Aktar",
                            Position = "Support Assistant",
                            State = "Georgia",
                            Title = "Mr."
                        },
                        new
                        {
                            EmployeeId = 74,
                            BirthDate = new DateTime(1958, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anton",
                            HireDate = new DateTime(1985, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Metelyov",
                            Position = "Support Assistant",
                            State = "Idaho",
                            Title = "Mr."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
